# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ThemeManagerDemo' do
pod 'UIColor-HexString', '~> 1.3.0'
end

target 'ThemeManagerDemoTests' do

end

target 'Assets' do

end

